/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SelectorRouteImport } from './routes/selector'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PassageiroDashboardRouteImport } from './routes/passageiro.dashboard'
import { Route as PassageiroAuthRouteImport } from './routes/passageiro.auth'
import { Route as MotoristaDashboardRouteImport } from './routes/motorista.dashboard'
import { Route as MotoristaAuthRouteImport } from './routes/motorista.auth'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectorRoute = SelectorRouteImport.update({
  id: '/selector',
  path: '/selector',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassageiroDashboardRoute = PassageiroDashboardRouteImport.update({
  id: '/passageiro/dashboard',
  path: '/passageiro/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PassageiroAuthRoute = PassageiroAuthRouteImport.update({
  id: '/passageiro/auth',
  path: '/passageiro/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaDashboardRoute = MotoristaDashboardRouteImport.update({
  id: '/motorista/dashboard',
  path: '/motorista/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristaAuthRoute = MotoristaAuthRouteImport.update({
  id: '/motorista/auth',
  path: '/motorista/auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/selector': typeof SelectorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/motorista/auth': typeof MotoristaAuthRoute
  '/motorista/dashboard': typeof MotoristaDashboardRoute
  '/passageiro/auth': typeof PassageiroAuthRoute
  '/passageiro/dashboard': typeof PassageiroDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/selector': typeof SelectorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/motorista/auth': typeof MotoristaAuthRoute
  '/motorista/dashboard': typeof MotoristaDashboardRoute
  '/passageiro/auth': typeof PassageiroAuthRoute
  '/passageiro/dashboard': typeof PassageiroDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/selector': typeof SelectorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/motorista/auth': typeof MotoristaAuthRoute
  '/motorista/dashboard': typeof MotoristaDashboardRoute
  '/passageiro/auth': typeof PassageiroAuthRoute
  '/passageiro/dashboard': typeof PassageiroDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/selector'
    | '/sitemap.xml'
    | '/motorista/auth'
    | '/motorista/dashboard'
    | '/passageiro/auth'
    | '/passageiro/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/selector'
    | '/sitemap.xml'
    | '/motorista/auth'
    | '/motorista/dashboard'
    | '/passageiro/auth'
    | '/passageiro/dashboard'
  id:
    | '__root__'
    | '/'
    | '/selector'
    | '/sitemap.xml'
    | '/motorista/auth'
    | '/motorista/dashboard'
    | '/passageiro/auth'
    | '/passageiro/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SelectorRoute: typeof SelectorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  MotoristaAuthRoute: typeof MotoristaAuthRoute
  MotoristaDashboardRoute: typeof MotoristaDashboardRoute
  PassageiroAuthRoute: typeof PassageiroAuthRoute
  PassageiroDashboardRoute: typeof PassageiroDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selector': {
      id: '/selector'
      path: '/selector'
      fullPath: '/selector'
      preLoaderRoute: typeof SelectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passageiro/dashboard': {
      id: '/passageiro/dashboard'
      path: '/passageiro/dashboard'
      fullPath: '/passageiro/dashboard'
      preLoaderRoute: typeof PassageiroDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passageiro/auth': {
      id: '/passageiro/auth'
      path: '/passageiro/auth'
      fullPath: '/passageiro/auth'
      preLoaderRoute: typeof PassageiroAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista/dashboard': {
      id: '/motorista/dashboard'
      path: '/motorista/dashboard'
      fullPath: '/motorista/dashboard'
      preLoaderRoute: typeof MotoristaDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorista/auth': {
      id: '/motorista/auth'
      path: '/motorista/auth'
      fullPath: '/motorista/auth'
      preLoaderRoute: typeof MotoristaAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SelectorRoute: SelectorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  MotoristaAuthRoute: MotoristaAuthRoute,
  MotoristaDashboardRoute: MotoristaDashboardRoute,
  PassageiroAuthRoute: PassageiroAuthRoute,
  PassageiroDashboardRoute: PassageiroDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
